### ISSUE TITLE
关于静音段的预处理

### ISSUE THREAD

**Issue by innnky** [shang0712/HierTTS#2]
我研究您给出的示例数据，发现其中似乎并没有sp等静音段，如这句”魏屯乡“中的 ”iang1"音素，后面应该有
一个短暂的停顿，然而标注的音素序列中并没有sp，标注的alignment中经过换算约从0.5s-0.9s部分均属于iang1音素。
因此按照这个逻辑，是否预处理中，静音段的处理便是直接将其合并到前一个元音中去呢
<img width="690" alt="iShot_2023-03-16_09 38 48" src="https://user-images.githubusercontent.com/67028263/225488094-eea0c24e-4725-4f9a-83a1-5651e7c4c3ad.png">

**Comment by shang0712** [comment]
> 我研究您给出的示例数据，发现其中似乎并没有sp等静音段，如这句”魏屯乡“中的 ”iang1"音素，后面应该有 一个短暂的停顿，然而标注的音素序列中并没有sp，标注的alignment中经过换算约从0.5s-0.9s部分均属于iang1音素。 因此按照这个逻辑，是否预处理中，静音段的处理便是直接将其合并到前一个元音中去呢 <img alt="iShot_2023-03-16_09 38 48" width="690" src="https://user-images.githubusercontent.com/67028263/225488094-eea0c24e-4725-4f9a-83a1-5651e7c4c3ad.png">

这句话中sp没有分出来可能是对齐工具的问题，sp并没有合并到元音上。我找了另外一条带sp的文本可以对照下，希望能够帮到你。
000773|{zh e4 m ei2 ii iu3 uu uang2 f a3 l e5} {b a3 uu ua2 zh en1 z ao1 t a4}|{zh e4 1 m ei2 ii iu3 1 uu uang2 f a3 l e5 1 b a3 uu ua2 1 zh en1 z ao1 t a4 1}|1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1|这#1没有#1王法了#1，把娃#1真糟蹋#1。|这没有王法了，把娃真糟蹋。|0 1 1 1 1 1 1 0 1 1 1 1 1 0 0|2 2 2 2 2 2 1 2 2 2 2 2|101 5511 3196 2804 3677 3220 647 6294 2413 1731 3951 4318 5427 545 102|[CLS] 这 没 有 王 法 了 ， 把 娃 真 糟 蹋 。 [SEP]|1 2 3 1 2 3|1 1 1 1 1|0 1 2 3 4 5 -1 6 7 8 9 10

**Comment by innnky** [comment]
感谢！

**Comment by innnky** [comment]
你好，关于数据的预处理，我还有最后一个疑惑，是关于分词的。我看到论文中说是使用pkuseg进行分词，然而数据的示例以及你前面给出的这条的分词似乎并不是按照pkuseg中seg.cut()方法的返回值来的。如上面的例句pkuseg默认模型的分词结果是['这', '没有', '王法', '了', '，', '把', '娃', '真', '糟蹋', '。']，请问是采用了什么规则对分词结果进行了合并吗

**Comment by shang0712** [comment]
> 你好，关于数据的预处理，我还有最后一个疑惑，是关于分词的。我看到论文中说是使用pkuseg进行分词，然而数据的示例以及你前面给出的这条的分词似乎并不是按照pkuseg中seg.cut()方法的返回值来的。如上面的例句pkuseg默认模型的分词结果是['这', '没有', '王法', '了', '，', '把', '娃', '真', '糟蹋', '。']，请问是采用了什么规则对分词结果进行了合并吗

这批数据生成在分词结果之后又接了一个韵律词#1的预测模型，你可以直接用分词结果作为#1训练

**Comment by innnky** [comment]
好的，我明白了，感谢！
